# Generated by Django 4.2.27 on 2026-01-06 16:35

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('supabase_uid', models.CharField(blank=True, help_text='Supabase user ID from Google OAuth', max_length=255, null=True, unique=True)),
                ('role', models.CharField(choices=[('admin', 'Admin/NGO'), ('donor', 'Donor'), ('beneficiary', 'Beneficiary'), ('auditor', 'Auditor'), ('merchant', 'Merchant')], default='donor', help_text="User's role in the system", max_length=20)),
                ('full_name', models.CharField(blank=True, max_length=255)),
                ('phone_number', models.CharField(blank=True, max_length=20)),
                ('organization', models.CharField(blank=True, help_text='NGO or organization name', max_length=255)),
                ('avatar_url', models.URLField(blank=True)),
                ('verification_status', models.CharField(choices=[('pending', 'Pending Verification'), ('verified', 'Verified'), ('rejected', 'Rejected'), ('suspended', 'Suspended')], default='pending', max_length=20)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BeneficiaryProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('region', models.CharField(help_text='Disaster-affected region', max_length=255)),
                ('address', models.TextField(blank=True, help_text='Physical address')),
                ('coordinates', models.CharField(blank=True, help_text='GPS coordinates', max_length=50)),
                ('household_size', models.PositiveIntegerField(default=1)),
                ('has_children', models.BooleanField(default=False)),
                ('has_elderly', models.BooleanField(default=False)),
                ('has_disabled', models.BooleanField(default=False)),
                ('needs_food', models.BooleanField(default=True)),
                ('needs_medical', models.BooleanField(default=False)),
                ('needs_shelter', models.BooleanField(default=False)),
                ('special_needs', models.TextField(blank=True)),
                ('risk_score', models.FloatField(default=0.0, help_text='ML-computed risk/priority score')),
                ('risk_factors', models.JSONField(blank=True, default=dict)),
                ('id_document_type', models.CharField(blank=True, max_length=50)),
                ('id_document_hash', models.CharField(blank=True, help_text='Hash of ID document for verification', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Beneficiary Profile',
                'verbose_name_plural': 'Beneficiary Profiles',
            },
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('address', models.CharField(help_text='Ethereum wallet address', max_length=42, unique=True, validators=[django.core.validators.RegexValidator(message='Enter a valid Ethereum address', regex='^0x[a-fA-F0-9]{40}$')])),
                ('is_primary', models.BooleanField(default=False, help_text='Primary wallet for receiving funds')),
                ('is_whitelisted', models.BooleanField(default=False, help_text='Whitelisted on-chain for receiving relief funds')),
                ('whitelisted_at', models.DateTimeField(blank=True, null=True)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('on_chain_balance', models.DecimalField(decimal_places=6, default=0, help_text='Last known on-chain balance', max_digits=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wallets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Wallet',
                'verbose_name_plural': 'Wallets',
                'ordering': ['-is_primary', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MerchantProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('business_name', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('food', 'Food & Groceries'), ('medical', 'Medical & Healthcare'), ('shelter', 'Shelter & Housing'), ('utilities', 'Utilities'), ('transport', 'Transportation')], max_length=20)),
                ('business_address', models.TextField()),
                ('business_license', models.CharField(blank=True, max_length=100)),
                ('is_registered_on_chain', models.BooleanField(default=False)),
                ('registered_on_chain_at', models.DateTimeField(blank=True, null=True)),
                ('total_received', models.DecimalField(decimal_places=6, default=0, max_digits=20)),
                ('transaction_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='merchant_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Merchant Profile',
                'verbose_name_plural': 'Merchant Profiles',
            },
        ),
    ]
