# Generated by Django 4.2.27 on 2026-01-09 07:54

import django.core.validators
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApprovedMerchant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('wallet_address', models.CharField(help_text='Ethereum wallet address of the merchant', max_length=42, unique=True, validators=[django.core.validators.RegexValidator(message='Enter a valid Ethereum address', regex='^0x[a-fA-F0-9]{40}$')])),
                ('business_name', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('food', 'Food & Groceries'), ('medical', 'Medical & Healthcare'), ('shelter', 'Shelter & Housing'), ('utilities', 'Utilities'), ('transport', 'Transportation')], max_length=20)),
                ('business_address', models.TextField()),
                ('business_license', models.CharField(blank=True, max_length=100)),
                ('is_registered_on_chain', models.BooleanField(default=False)),
                ('registered_on_chain_at', models.DateTimeField(blank=True, null=True)),
                ('total_received', models.DecimalField(decimal_places=6, default=0, max_digits=20)),
                ('transaction_count', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Approved Merchant',
                'verbose_name_plural': 'Approved Merchants',
            },
        ),
        migrations.RemoveField(
            model_name='merchantprofile',
            name='user',
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin/NGO'), ('donor', 'Donor'), ('beneficiary', 'Beneficiary'), ('auditor', 'Auditor')], default='donor', help_text="User's role in the system", max_length=20),
        ),
    ]
