# Generated by Django 4.2.27 on 2026-01-09 07:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_alter_transactionlog_merchant'),
        ('accounts', '0003_approvedmerchant_remove_merchantprofile_user_and_more'),
        ('campaigns', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MerchantProfile',
        ),
        migrations.AddField(
            model_name='approvedmerchant',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_merchants', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='approvedmerchant',
            name='campaigns',
            field=models.ManyToManyField(blank=True, related_name='approved_merchants', to='campaigns.aidcampaign'),
        ),
    ]
