# Generated by Django 4.2.27 on 2026-01-06 16:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AidCampaign',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('region', models.CharField(help_text='Affected geographic region', max_length=255)),
                ('disaster_type', models.CharField(choices=[('earthquake', 'Earthquake'), ('flood', 'Flood'), ('hurricane', 'Hurricane'), ('wildfire', 'Wildfire'), ('pandemic', 'Pandemic'), ('conflict', 'Conflict'), ('drought', 'Drought'), ('other', 'Other')], max_length=20)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('paused', 'Paused'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('target_amount', models.DecimalField(decimal_places=6, help_text='Target amount in drUSD', max_digits=20)),
                ('raised_amount', models.DecimalField(decimal_places=6, default=0, help_text='Total amount raised/minted', max_digits=20)),
                ('distributed_amount', models.DecimalField(decimal_places=6, default=0, help_text='Amount distributed to beneficiaries', max_digits=20)),
                ('spent_amount', models.DecimalField(decimal_places=6, default=0, help_text='Amount spent by beneficiaries', max_digits=20)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('on_chain_id', models.CharField(blank=True, help_text='Campaign ID on the blockchain', max_length=100)),
                ('image_url', models.URLField(blank=True)),
                ('metadata_uri', models.URLField(blank=True, help_text='IPFS URI for additional metadata')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_campaigns', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Aid Campaign',
                'verbose_name_plural': 'Aid Campaigns',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=6, max_digits=20)),
                ('currency', models.CharField(default='USD', max_length=10)),
                ('is_anonymous', models.BooleanField(default=False)),
                ('message', models.TextField(blank=True)),
                ('donated_at', models.DateTimeField(auto_now_add=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donations', to='campaigns.aidcampaign')),
                ('donor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='donations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-donated_at'],
            },
        ),
        migrations.CreateModel(
            name='FundAllocation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('total_amount', models.DecimalField(decimal_places=6, max_digits=20)),
                ('distributed_amount', models.DecimalField(decimal_places=6, default=0, max_digits=20)),
                ('food_allowance', models.DecimalField(decimal_places=6, default=0, max_digits=20)),
                ('medical_allowance', models.DecimalField(decimal_places=6, default=0, max_digits=20)),
                ('shelter_allowance', models.DecimalField(decimal_places=6, default=0, max_digits=20)),
                ('utilities_allowance', models.DecimalField(decimal_places=6, default=0, max_digits=20)),
                ('transport_allowance', models.DecimalField(decimal_places=6, default=0, max_digits=20)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('allocated_at', models.DateTimeField(auto_now_add=True)),
                ('distributed_at', models.DateTimeField(blank=True, null=True)),
                ('distribution_tx_hash', models.CharField(blank=True, max_length=66)),
                ('beneficiary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='accounts.beneficiaryprofile')),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='campaigns.aidcampaign')),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='accounts.wallet')),
            ],
            options={
                'verbose_name': 'Fund Allocation',
                'verbose_name_plural': 'Fund Allocations',
                'unique_together': {('campaign', 'beneficiary')},
            },
        ),
        migrations.CreateModel(
            name='CategorySpendingLimit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('category', models.CharField(choices=[('food', 'Food & Groceries'), ('medical', 'Medical & Healthcare'), ('shelter', 'Shelter & Housing'), ('utilities', 'Utilities'), ('transport', 'Transportation')], max_length=20)),
                ('max_per_transaction', models.DecimalField(decimal_places=6, max_digits=20)),
                ('max_daily', models.DecimalField(decimal_places=6, max_digits=20)),
                ('max_total', models.DecimalField(decimal_places=6, max_digits=20)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spending_limits', to='campaigns.aidcampaign')),
            ],
            options={
                'unique_together': {('campaign', 'category')},
            },
        ),
    ]
