# Generated by Django 4.2.27 on 2026-01-06 16:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('campaigns', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('transaction_type', models.CharField(choices=[('mint', 'Fund Minting'), ('distribute', 'Fund Distribution'), ('spend', 'Beneficiary Spending'), ('transfer', 'Token Transfer'), ('refund', 'Refund')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('tx_hash', models.CharField(blank=True, max_length=66, null=True, unique=True)),
                ('block_number', models.PositiveBigIntegerField(blank=True, null=True)),
                ('chain_id', models.PositiveIntegerField(default=11155111)),
                ('from_address', models.CharField(max_length=42)),
                ('to_address', models.CharField(max_length=42)),
                ('amount', models.DecimalField(decimal_places=6, max_digits=30)),
                ('category', models.CharField(blank=True, max_length=20)),
                ('reference', models.CharField(blank=True, max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('gas_used', models.PositiveBigIntegerField(blank=True, null=True)),
                ('gas_price', models.PositiveBigIntegerField(blank=True, null=True)),
                ('is_flagged', models.BooleanField(default=False)),
                ('flag_reason', models.TextField(blank=True)),
                ('fraud_score', models.FloatField(default=0.0)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('allocation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='campaigns.fundallocation')),
                ('merchant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_transactions', to='accounts.merchantprofile')),
                ('wallet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='accounts.wallet')),
            ],
            options={
                'verbose_name': 'Transaction Log',
                'verbose_name_plural': 'Transaction Logs',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='SpendingAnalytics',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('food_spent', models.DecimalField(decimal_places=6, default=0, max_digits=20)),
                ('medical_spent', models.DecimalField(decimal_places=6, default=0, max_digits=20)),
                ('shelter_spent', models.DecimalField(decimal_places=6, default=0, max_digits=20)),
                ('utilities_spent', models.DecimalField(decimal_places=6, default=0, max_digits=20)),
                ('transport_spent', models.DecimalField(decimal_places=6, default=0, max_digits=20)),
                ('transaction_count', models.PositiveIntegerField(default=0)),
                ('unique_beneficiaries', models.PositiveIntegerField(default=0)),
                ('unique_merchants', models.PositiveIntegerField(default=0)),
                ('flagged_transactions', models.PositiveIntegerField(default=0)),
                ('campaign', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='analytics', to='campaigns.aidcampaign')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='BlockchainSync',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('chain_id', models.PositiveIntegerField()),
                ('contract_address', models.CharField(max_length=42)),
                ('last_synced_block', models.PositiveBigIntegerField(default=0)),
                ('last_synced_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'unique_together': {('chain_id', 'contract_address')},
            },
        ),
        migrations.CreateModel(
            name='AuditEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('campaign', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_events', to='campaigns.aidcampaign')),
                ('transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_events', to='transactions.transactionlog')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AddIndex(
            model_name='transactionlog',
            index=models.Index(fields=['tx_hash'], name='transaction_tx_hash_61822b_idx'),
        ),
        migrations.AddIndex(
            model_name='transactionlog',
            index=models.Index(fields=['from_address'], name='transaction_from_ad_fe5ad2_idx'),
        ),
        migrations.AddIndex(
            model_name='transactionlog',
            index=models.Index(fields=['to_address'], name='transaction_to_addr_356693_idx'),
        ),
        migrations.AddIndex(
            model_name='transactionlog',
            index=models.Index(fields=['timestamp'], name='transaction_timesta_637ae0_idx'),
        ),
        migrations.AddIndex(
            model_name='transactionlog',
            index=models.Index(fields=['transaction_type'], name='transaction_transac_0f57d1_idx'),
        ),
        migrations.AddIndex(
            model_name='transactionlog',
            index=models.Index(fields=['is_flagged'], name='transaction_is_flag_9d531d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='spendinganalytics',
            unique_together={('date', 'campaign')},
        ),
    ]
